[package]
name = "report-generation" 
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
derivative = "2.2.0"
fxhash = "0.2.1"
indexmap = "2.2.6"
lazy_static = "1.4"
rand = "0.8.5"
serde = "1.0.201"
serde_derive = "1.0.201"
tempfile = "3.10.1"
tinyset = "0.4.15"